### ISSUE TITLE
Estudo da API do github

### ISSUE THREAD

**Issue by Tiago1604** [fga-eps-mds/2023.1-PyAnalyticsGit#21]
## Descrição 
É necessário achar informações e estudarmos a respeito da API do github para desenvolver o projeto.

## Tarefas

- [ ] Achar informações e compartilhar com os integrantes **(Atualizar 'Recursos')**
- [ ] Estudar a respeito da API

## Critérios de Aceitação
**Todos os membros devem ter realizado as tarefas:**

- [x] Gabriel
- [x] Jefferson
- [x] Mateus
- [x] Pedro
- [x] Rodrigo
- [x] Tiago

**Comment by mateus9levy** [comment]
Estudando...
